name: Axi Stream Test
run-name: ${{ github.actor }} is testing out Axi Stream
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
    
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: echo "Accessing Docker Hub......"

    - name: Pull cocotb Docker image
      run: docker pull sherlocat/cocotb
    - run: echo "Pulling Dockerfile"

    - name: Run cocotb Docker image
      run: docker run -v $(pwd)/AXI_Stream:/home/project sherlocat/cocotb make
    - run: cd ./AXI_Stream/output
    - run: ls
    
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: axi-test-report
        path: ./AXI_Stream/output