name: Axi Stream Test
run-name: ${{ github.actor }} is testing out Axi Stream
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
    
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: echo "Accessing Docker Hub......"

    - name: Build Docker image
      run: docker build --progress=plain -t cocotb:axi .
    - run: echo "Running Dockerfile"